### ISSUE TITLE
Lbx Reverse Engineering Data

### ISSUE THREAD

**Issue by GendoIkari** [verokarhu/gorion2#1]
Maybe this is not a real github Issue, but I'm working right know on lbxs, and I'm watching your project. Where are you finding lbx infos? I mean, apart from the few infos easy to find with google, like the main header, the sound format, the array and the animation format.
Thank you in advance.

**Comment by verokarhu** [comment]
I'm using mostly information from a cached copy of [wolverine's blog](http://web.archive.org/web/20131025194034/http://www.karoltomala.com/blog/?category_name=master-of-orion-2) and a mirror of some of the same content on the [master of orion 2 blog](http://masteroforion2.blogspot.fi/2008/04/moo2-graphics.html).

LBX parsing/Moo2 rewriting seems like a popular hobby. :)
